# Generated by Django 4.1.3 on 2022-11-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da lista')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Factory_Cheese.listsystem')),
            ],
        ),
        migrations.AddField(
            model_name='listsystem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Factory_Cheese.seller'),
        ),
    ]
